openapi: 3.0.1
info:
  title: Sample
  description: ''
  version: v1
servers:
  - url: https://souvik-dev-pox.azure-api.net/v1
paths:
  /v1/myresource:
    get:
      summary: GetName
      description: GetName
      operationId: getname
      responses:
        '200':
          description: ''
    post:
      summary: PostName
      description: PostName
      operationId: postname
      responses:
        '200':
          description: ''
  /v1/myResource:
    delete:
      summary: del
      description: del
      operationId: del
      responses:
        '200':
          description: ''
  /myResourcev1:
    get:
      summary: Nice
      operationId: nice
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
