openapi: 3.0.1
info:
  title: Sample
  description: ''
  version: 'v1'
servers:
  - url: https://souvik-dev-pox.azure-api.net
paths:
  /myresource:
    get:
      summary: GetName
      description: GetName
      operationId: getname
      responses:
        '200':
          description: ''
  /myResource:
    delete:
      summary: del
      description: del
      operationId: del
      parameters:
        - name: myHeader
          in: header
          description: Sample
          schema:
            type: string
      responses:
        '200':
          description: ''
  /myResourcev1:
    get:
      summary: Verynice
      operationId: verynice
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
